SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[Table1] (
		[Column1]     [int] NOT NULL,
		[Column2]     [int] NOT NULL,
		CONSTRAINT [PK__Table1__529C02D5C54D981F]
		PRIMARY KEY
		NONCLUSTERED
		([Column1])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Table1]
	WITH NOCHECK
	ADD
	CONSTRAINT [CK__Table1__Column1__3C69FB99]
	CHECK
	NOT FOR REPLICATION
	([Column1]>=(1) AND [Column1]<=(999))
GO
ALTER TABLE [dbo].[Table1]
CHECK CONSTRAINT [CK__Table1__Column1__3C69FB99]
GO
ALTER TABLE [dbo].[Table1] SET (LOCK_ESCALATION = TABLE)
GO
