SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TESTbre] (
		[rrr]     [int] NOT NULL,
		[aaa]     [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [PK_TESTbre]
		PRIMARY KEY
		CLUSTERED
		([rrr])
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TESTbre] SET (LOCK_ESCALATION = TABLE)
GO
