SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[TestTriggers] (
		[Date]     [date] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TestTriggers] SET (LOCK_ESCALATION = TABLE)
GO
