SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Movies] (
		[MovieId]       [int] IDENTITY(1, 1) NOT NULL,
		[MovieName]     [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		CONSTRAINT [PK__Movies__4BD2941AC0A2B023]
		PRIMARY KEY
		CLUSTERED
		([MovieId])
	WITH (	DATA_COMPRESSION = PAGE)
	ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Movies] SET (LOCK_ESCALATION = TABLE)
GO
