SET IDENTITY_INSERT [HumanResources].[Department] ON
INSERT INTO [HumanResources].[Department] ([DepartmentID], [Name], [GroupName], [ModifiedDate], [NEW]) VALUES (1, N'Engineering', N'Research and Development', '20080430 00:00:00.000', NULL)
INSERT INTO [HumanResources].[Department] ([DepartmentID], [Name], [GroupName], [ModifiedDate], [NEW]) VALUES (2, N'Tool Design', N'Research and Development', '20080430 00:00:00.000', NULL)
INSERT INTO [HumanResources].[Department] ([DepartmentID], [Name], [GroupName], [ModifiedDate], [NEW]) VALUES (3, N'Sales', N'Sales and Marketing', '20080430 00:00:00.000', NULL)
INSERT INTO [HumanResources].[Department] ([DepartmentID], [Name], [GroupName], [ModifiedDate], [NEW]) VALUES (4, N'Marketing', N'Sales and Marketing', '20080430 00:00:00.000', NULL)
INSERT INTO [HumanResources].[Department] ([DepartmentID], [Name], [GroupName], [ModifiedDate], [NEW]) VALUES (5, N'Purchasing', N'Inventory Management', '20080430 00:00:00.000', NULL)
INSERT INTO [HumanResources].[Department] ([DepartmentID], [Name], [GroupName], [ModifiedDate], [NEW]) VALUES (6, N'Research and Development', N'Research and Development', '20080430 00:00:00.000', NULL)
INSERT INTO [HumanResources].[Department] ([DepartmentID], [Name], [GroupName], [ModifiedDate], [NEW]) VALUES (7, N'Production', N'Manufacturing', '20080430 00:00:00.000', NULL)
INSERT INTO [HumanResources].[Department] ([DepartmentID], [Name], [GroupName], [ModifiedDate], [NEW]) VALUES (8, N'Production Control', N'Manufacturing', '20080430 00:00:00.000', NULL)
INSERT INTO [HumanResources].[Department] ([DepartmentID], [Name], [GroupName], [ModifiedDate], [NEW]) VALUES (9, N'Human Resources', N'Executive General and Administration', '20080430 00:00:00.000', NULL)
INSERT INTO [HumanResources].[Department] ([DepartmentID], [Name], [GroupName], [ModifiedDate], [NEW]) VALUES (10, N'Finance', N'Executive General and Administration', '20080430 00:00:00.000', NULL)
INSERT INTO [HumanResources].[Department] ([DepartmentID], [Name], [GroupName], [ModifiedDate], [NEW]) VALUES (11, N'Information Services', N'Executive General and Administration', '20080430 00:00:00.000', NULL)
INSERT INTO [HumanResources].[Department] ([DepartmentID], [Name], [GroupName], [ModifiedDate], [NEW]) VALUES (12, N'Document Control', N'Quality Assurance', '20080430 00:00:00.000', NULL)
INSERT INTO [HumanResources].[Department] ([DepartmentID], [Name], [GroupName], [ModifiedDate], [NEW]) VALUES (13, N'Quality Assurance', N'Quality Assurance', '20080430 00:00:00.000', NULL)
INSERT INTO [HumanResources].[Department] ([DepartmentID], [Name], [GroupName], [ModifiedDate], [NEW]) VALUES (14, N'Facilities and Maintenance', N'Executive General and Administration', '20080430 00:00:00.000', NULL)
INSERT INTO [HumanResources].[Department] ([DepartmentID], [Name], [GroupName], [ModifiedDate], [NEW]) VALUES (15, N'Shipping and Receiving', N'Inventory Management', '20080430 00:00:00.000', NULL)
INSERT INTO [HumanResources].[Department] ([DepartmentID], [Name], [GroupName], [ModifiedDate], [NEW]) VALUES (16, N'Executive', N'Executive General and Administration', '20080430 00:00:00.000', NULL)
SET IDENTITY_INSERT [HumanResources].[Department] OFF
